set -g prefix C-Space
unbind C-b
bind C-Space send-prefix
#start with 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-L next-window
bind -n M-H previous-window

bind i source-file ~/.config/tmux/tmux.conf
set -g status-style 'bg=colour232 fg=colour255'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set-option -g default-shell "/usr/bin/bash"
set-option -g default-command bash


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
